### ISSUE TITLE
Define OpenGov parameters for Paseo.

### ISSUE THREAD

**Issue by hbulgarini** [paseo-network/paseo-rfcs#1]
# Paseo OpenGov Paramenters 

This issue marks the beginning of our discussion about the OpenGov parameters for the Paseo Network.

A key design decision is to initially reject all OpenGov proposals by default. This strategy is to prevent any misuse stemming from privileged origins. However, if a testing scenario necessitates the use of OpenGov, this restriction may be reconsidered and potentially lifted for that specific instance. In most cases, a bot with sudo access should be capable of overriding this default setting.

During our initial discussions with the founding members of Paseo, it was agreed that the runtime specifications should align as closely as possible with those of the Polkadot network. The most straightforward method would be to adopt the same parameters as Polkadot, which can be found here: [Polkadot Runtime Parameters](https://wiki.polkadot.network/docs/learn-polkadot-opengov-origins#origins-and-tracks-info). Alternatively, we could explore a custom implementation with accelerated processing, although this would require thorough analysis. Any such implementation must allow sufficient time for a bot or application to identify and eliminate any unauthorized proposals.

Here are some advantages and disadvantages of using Polkadot's parameters:

Advantages:
- Enough time to identify and eliminate harmful proposals.
- Reduced need for frequent updates to the runtime.

Disadvantages:
- Even approved proposals must face the lengthy processing times associated with Polkadot's OpenGov parameters.

**Comment by hbulgarini** [comment]
My personal preference is to have the same parameters as Polkadot, mostly taking into account that we want to disallow the usage of OpenGov and in case root origin is required, we can use sudo.

**Comment by al3mart** [comment]
https://github.com/paseo-network/runtimes/pull/1

Can we close this issue ?
