### ISSUE TITLE
RFC - Create paseo-network/support repository

### ISSUE THREAD

**Issue by educlerici-zondax** [paseo-network/paseo-rfcs#15]
### Introduction
This RFC proposes the creation of a new repository within the paseo-network organization on GitHub, named support. The purpose of this repository is to centralize and streamline the process of handling support requests, issues, and inquiries from the public and contributors.

### Description of the Process
**1. Repository Creation**

- A new repository named paseo-network/support will be created.
- This repository will serve as the primary point of contact for external support requests related to the paseo-network.

**2. Issue Creation**

- The public and contributors will be encouraged to create issues in this repository for all support-related inquiries.
- Issues can range from bug reports, feature requests, documentation improvements, and general questions related to the project.

**3. Issue Triage**

- Zondax will be responsible for the daily triage of incoming issues.
- The triage process will involve reviewing, categorizing, and prioritizing the issues.
- Necessary labels will be applied to each issue to facilitate efficient issue management.

**4. Issue Resolution**

- Issues will be addressed according to their priority and nature.
- The community and team members can contribute to issue discussions and resolutions.
- Resolved issues will be closed with a summary comment explaining the resolution or outcome.

**5. Regular Updates**

- Regular updates on the status of open issues will be provided to maintain transparency with the community.

**6. Create a Readme File to Explain how to use it**

- The README will outline the purpose of the repository and provide detailed instructions on how to create an issue.
- It will also explain the issue triage and resolution process, so users are aware of what to expect after submitting their issues.
- Contact information and links to additional resources, such as FAQs or documentation, will be included.

**7. Service Level Agreement (Support)**

The workflow to acknowledge and resolve support tickets within specified time frames will be the following.

- Support Ticket Handling
  - **Acknowledgment** : Within 24 hours.
  - **Resolution** : Mean time of 72 hours (_varies based on complexity and triage_)

**Comment by educlerici-zondax** [comment]
LGTM! already added!

**Comment by hbulgarini** [comment]
@educlerici-zondax i think the issue description is good enough to proceed with the PR , wdyt?
