### ISSUE TITLE
RFC - Create paseo-network/support Wiki

### ISSUE THREAD

**Issue by educlerici-zondax** [paseo-network/paseo-rfcs#16]
### Introduction
This RFC proposes the establishment of a dedicated wiki within the paseo-network community. The primary goal of this wiki is to serve as an exhaustive resource for documentation, addressing various aspects of the network, ranging from technical guidelines to general information.

### Linked RFCs
This RFC will be linked with the [#15 RFC - Create paseo-network/support repository](https://github.com/paseo-network/paseo-rfcs/issues/15)

### Purpose

- **Centralized Knowledge Base:** To consolidate all informational resources about paseo-network into a single, easily navigable platform.

- **Community Support**: To aid new and existing users and developers by providing clear and concise documentation, thereby enhancing their experience and understanding of the network.

- **Collaborative Documentation**: To create an environment where the community can contribute to and evolve the documentation, ensuring its accuracy and relevance.

### Documentation Topics
The wiki will encompass a broad range of topics, some of them as an example may be the following:

- **Document Addresses**: Guidelines on how to interact with key network addresses, including node addresses, contract addresses, and other critical endpoints.

- **Multisig Account Management**: Detailed instructions on creating and managing multisig accounts, highlighting their significance in enhancing security and operational procedures within the network.

- **Bootstrap Nodes**: Information on bootstrap nodes, their role in the network, how to connect to them, and their importance for network stability and performance.

- **Links to Code Files**: Direct links to relevant GitHub repositories, code files, and development resources, facilitating easier access for developers and contributors.

- **Contributor Guidelines**: Include contributor guidelines to maintain the same structure and components on every Document added by contributors.

### Structure and Accessibility

- The wiki will be structured in a user-friendly manner, with clear categorization and search functionality.

- It will be accessible to the entire paseo-network community and will encourage contributions from members to keep the content updated and accurate.

### Community Engagement

- The community will be encouraged to contribute to the wiki, either by adding new content, updating existing content, or suggesting improvements.

- A process for content submission and review will be established to maintain the quality and accuracy of the information.

**Comment by al3mart** [comment]
Along with any needed documentation for Paseo I would be great to include contributor guidelines.

**Comment by al3mart** [comment]
Created the support repo and included a draft with some initial documentation
https://github.com/paseo-network/support/pull/1

**Comment by educlerici-zondax** [comment]
@al3mart thanks! already updated with contributor guidelines bulletpoint
