### ISSUE TITLE
RFC - Team Call Schedule for paseo-network

### ISSUE THREAD

**Issue by educlerici-zondax** [paseo-network/paseo-rfcs#18]
### Introduction
This RFC proposes the implementation of a regular schedule for team calls within the paseo-network community. These calls are aimed at enhancing coordination, communication, and collaboration among team members. A set schedule will ensure regular and effective touchpoints for various aspects of the project.

### Proposed Schedule: 
The team call schedule will be as follows:

**Tuesdays - Core Team Call**
Purpose: To discuss core development updates, address technical challenges, and plan for upcoming features or changes.
Participants: Core development team and technical leads. (Zondax, R0GUE and Portico, @helloitsbirdo optional)
Time: 2 PM CET.
Frequency: Weekly.

**Thursdays - Fellowship Coordination Call**
Purpose: To review the progress made during the week, discuss any blockers or challenges, and align on the goals for the next week.
Participants: team members, project fellows, and invited guests (as applicable).
Time: 2 PM CET.
Frequency: Bi-Weekly (Each two weeks).

### Call Format and Guidelines
- Each call will have a designated facilitator to guide the discussion.
- An agenda will be circulated at least 24 hours before the call.
- Team members are encouraged to add items to the agenda ahead of time.
- A summary of each call will be documented and shared with the team for reference and action points.
- Leave public notes if decisions were taken during the meet.

### Goals
- Enhanced Communication: Regular calls will ensure all team members are aligned and informed about the project's progress and challenges.
- Efficient Collaboration: Frequent meets will aid in quicker decision-making and problem resolution.
- Community Engagement: Monthly calls will provide an opportunity to engage with wider community members, gather feedback, and align on community-driven initiatives.

### Implementation
- A Google Calendar for the Paseo Network will be done so members can suscribe to it to be aligned with every Network Meet scheduled if they are able to join.
- Virtual meeting links (Zoom, Google Meet, etc.) will be included in the calendar invites.
- Reminders will be sent one day before each call.

**Comment by al3mart** [comment]
Nice! Makes sense. We might even want to leave some public notes of the decisions that were taken in those calls (?)

Just a nit, I'd refrain from calling this a fellowship.

**Comment by educlerici-zondax** [comment]
@al3mart nice one! already edited and added!

**Comment by hbulgarini** [comment]
Thanks @educlerici-zondax for setting this up.

I wonder if we really need two weekly calls for this:

```
Tuesdays - Core Team Call
Purpose: To discuss core development updates, address technical challenges, and plan for upcoming features or changes.
Participants: Core development team and technical leads.
Time: 2 PM CET.
Frequency: Weekly.

Thursdays - Internal Weekly Report Call
Purpose: To review the progress made during the week, discuss any blockers or challenges, and align on the goals for the next week.
Participants: All team members, including development, marketing, core team, etc.
Time: 2 PM CET.
Frequency: Weekly.
``` 

I agree that we should get together in a weekly sync call, but potentially we could merge these two into one.

About the `Monthly Fellowship Coordination Call`, i have nothing to say execept @helloitsbirdo has scheduled this every two weeks and maybe until Rococo is shutdown we would need a more frequent contact with other actors, as for example Parity and validators. 

So my suggestion:

Tuesdays - Core Team Call : 
Frequency: Weekly
Participatns: Zondax, R0GUE and Portico (@helloitsbirdo optional)

Thrusdays - Fellowship Coordination Call:
Frequency: Bi-Weekly
Participants: team members, project fellows, and invited guests (as applicable).

wdyt?

**Comment by educlerici-zondax** [comment]
@hbulgarini i agree! i will update the RFC asap

**Comment by hbulgarini** [comment]
> Thursdays - Fellowship Coordination Call:
<strike> Frequency: Bi-Weekly </strike>
> Participants: team members, project fellows, and invited guests (as applicable).

As discussed, this meeting initially will be weekly until Rococo is shutdown and then we can move it to Bi-Weekly or even Monthly.
